// This file has been autogenerated from a class added in the UI designer.

using System;
using Sylapse.AutofacPlatformInjection.iOS;

namespace MainSample.iOS
{
	public partial class FirstViewController : LifetimeViewController
	{
        [InjectViewDidLoad]
        private FirstViewModel _firstViewModel;

		public FirstViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }
    }
}
