// This file has been autogenerated from a class added in the UI designer.

using System;
using Sylapse.AutofacPlatformInjection.iOS;

namespace MainSample.iOS
{
    public partial class MainViewController : LifetimeViewController
    {
        [InjectViewDidLoad]
        private MainViewModel _mainViewModel;

        public MainViewController (IntPtr handle) : base (handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }
    }
}
